### ISSUE TITLE
Compatibility of HMCODE with gcc compiler

### ISSUE THREAD

**Issue by suhani0603** [alexander-mead/HMcode#3]
I was trying to run the latest HMCODE 2020, but I am getting the following error:

`suhani@suhani-Vostro-5490:~/HMcode$ ./bin/HMcode 0.32 0.049 0.67 0.97 0.81 -1.0 input/Planck_linearpower.dat`

```
 ASSIGN_COSMOLOGY: Assigning cosmological model parameters
 ASSIGN_COSMOLOGY: Cosmology: Boring
 ASSIGN_COSMOLOGY: Done

At line 201 of file library/src/basic_operations.f90
Fortran runtime error: End of file

Error termination. Backtrace:
#0  0x7fb09d28bd26 in list_formatted_read_scalar
at /home/rdonnelly/mc/conda-bld/compilers_linux-64_1534627447954/work/.build/x86_64-conda_cos6-linux-gnu/src/gcc/libgfortran/io/list_read.c:2308
#1  0x55ece56793ab in ???
#2  0x55ece5767db1 in ???
#3  0x55ece56784dc in ???
#4  0x7fb09ce28082 in ???
#5  0x55ece567853d in ???
#6  0xffffffffffffffff in ???
```

I tried to even check different versions of HMCODE for compatibility. I am getting same error message for all trials.
To download from github, I used: `git clone --recursive https://github.com/alexander-mead/HMcode`, and then make..this all executed successfully.

**Comment by suhani0603** [comment]
I was able to resolve this issue.
There was a compatibility issue of the gcc version on my system (9.4.0) with HMCODE. 
I upgraded the gcc (to 11.3.0) and now the code works.
I also updated by ubuntu, from 20.04 to 22.04.

**Comment by alexander-mead** [comment]
Great!! I'm glad you were able to resolve this.
